version: '2'

services:
  jupyter:
    image: 'jupyter/datascience-notebook'
    container_name: 'jupyter'
    ports:
      - '8888:8888'
    volumes:
      - './notebooks:/home/jovyan/notebooks'
    # environment:
    #   - ALLOW_ANONYMOUS_LOGIN=yes
