version: '2'
services:
  envoy:
    image: envoyproxy/envoy:v1.17-latest
    container_name: envoy
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

# networks: 
#   sol-docker:
#     external: true