version: '3.3'
services:
    minio:
        container_name: minio
        ports:
            - '9090:9000'
        image: minio/minio:latest
        volumes:
          - './data:/data'
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        command: server /data

