version: "3.3"
services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
  influxdb:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
      - 8089:8089/udp
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb-data:/var/lib/influxdb

volumes:
  grafana-data:
  influxdb-data: